# Generated by Django 3.2.4 on 2021-06-25 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
